GET http://localhost:5000/api/tts

###
POST http://localhost:5000/api/tts HTTP/1.1
content-type: application/json

{
    "authorization_token": "token",
    "user": "user",
    "text": "Hello cats from the outer outer space"
}

###

GET http://localhost:5000/audios/

###
POST http://localhost:5000/api/stt
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="file"; filename="1.wav"

Content-Type: audio/wav

------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

