GET http://localhost:5000/api/healthcheck

###

GET http://localhost:5000/api/tts

###
POST http://localhost:5000/api/tts HTTP/1.1
content-type: application/json

{
    "authorization_token": "token",
    "user": 1312,
    "text": "Hello cats from the outer outer space"
}

###

POST http://localhost:5000/api/stt
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

title: audio.test.wav
------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: name="file"; filename="audio.test.wav"
Content-Type: audio/wav

------WebKitFormBoundary7MA4YWxkTrZu0gW--

< ./audio.test.wav
###
